### ISSUE TITLE
Cannot create second Filesystem provider in v2.7.4

### ISSUE THREAD

**Issue by pereverti** [music-assistant/support#4801]
### What version of Music Assistant has the issue?

2.7.4

### How is the MA server installed?

Docker Container

### Carefully read the Troubleshooting FAQ and confirm that

- [x] I have examined the logs and tried to resolve this issue
- [x] I have fixed any errors in the logs that relate to tags
- [x] I am not running MA across a VPN, VLAN, subnet, behind a firewall, or using local SSL or have any other complex network setup
- [x] I have disabled tool such as AdGuard, Pi-hole or pfSense and retested
- [x] I have checked my network setup to ensure mDNS/multicast is not being blocked
- [x] If using HA, I have confirmed the internal URL is set correctly
- [x] I have tried a wired connection for issues related to interrupted or poor playback quality
- [x] If the problem relates to a device then I have checked the device settings
- [x] If it is a frontend issue, I have tried a different widely used browser
- [x] I have reviewed the applicable [player](https://www.music-assistant.io/player-support/) or [music provider](https://www.music-assistant.io/music-providers/) documentation
- [x] For voice problems, I have sought help elsewhere before returning here
- [x] For playback problems, I have recycled power to the physical device
- [x] I have tried restarting MA and rebooting the host

### Have you reviewed the [Open](https://github.com/music-assistant/support/issues) and [Closed](https://github.com/music-assistant/support/issues?q=is%3Aissue%20state%3Aclosed) Issues and [Discussions](https://github.com/orgs/music-assistant/discussions) to resolve this yourself?

- [x] Yes

### The problem

Version: 2.7.4
Previous working version: 2.7.3

### Description
After upgrading from 2.7.3 to 2.7.4, it's impossible to create a second Filesystem music provider. The first provider can be created successfully, but attempting to create a second one fails with a Python AttributeError.

### Steps to Reproduce
Upgrade Music Assistant from 2.7.3 to 2.7.4
Go to Settings → Music Providers
Create a first Filesystem provider (e.g., /music) → ✅ Works fine
Try to create a second Filesystem provider (e.g., /youtube-music) → ❌ Fails with error

### Error Message
'LocalFileSystemProvider' object has no attribute 'base_path'

### Expected Behavior
Should be able to create multiple Filesystem providers pointing to different directories, as was possible in v2.7.3.

### Actual Behavior
First Filesystem provider: Works
Second Filesystem provider: Fails with base_path AttributeError
This affects both new installations and upgrades where existing providers were deleted and recreated

### Workaround
Downgrade to v2.7.3 - multiple Filesystem providers work correctly.

### Environment
Music Assistant Version: 2.7.4
Installation method: Docker (ghcr.io/music-assistant/server:latest)
Platform: Unraid

### Docker mount configuration:
/mnt/user/Musique → /music (ro)
/mnt/user/Divers/Youtube Downloader/Musique → /youtube-music (ro)

### Music Providers

Filesystem provider

### Player Providers

N/A

### Full log output

N/A

### Additional information

N/A

### What version of Home Assistant Core (if used) are your running

2026.1.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

### Have you included ALL of the information specified in the Troubleshooting FAQ or explained why you cannot

- [x] Yes

**Comment by OzGav** [comment]
How is the attachment of the full log not applicable?

**Comment by halkeye** [comment]
Looks like its https://github.com/music-assistant/server/commit/7af16a90d8640bb4c0409a73237b9c64b7c2817c

looks like self.name needs base_path, but base_path isn't defined until after __init__returns (after super)
