### ISSUE TITLE
'Audiobookshelf' object has no attribute 'libraries'

### ISSUE THREAD

**Issue by TheZoker** [music-assistant/support#5924]
### Before you begin

- [x] I have searched the [open and closed issues](https://github.com/music-assistant/support/issues?q=is%3Aissue) and this hasn't been reported yet.
- [x] I have read the [troubleshooting guide](https://www.music-assistant.io/faq/troubleshooting/) and it did not solve my problem.
- [x] I am running a [supported installation](https://www.music-assistant.io/installation/) (Home Assistant add-on or Docker container).

### What happened?

Since the last update to 2.10.0b9 I get this error when trying to connect to Audiobookshelf:
'Audiobookshelf' object has no attribute 'libraries'

### How to reproduce

1. Go to Music source
2. Add Audiobookshelf

### Music Assistant version

2.10.0b9

### How do you run Music Assistant?

Home Assistant add-on

### Diagnostics report or log file

[music-assistant-diagnostics-2026-07-27-195509.json](https://github.com/user-attachments/files/30432211/music-assistant-diagnostics-2026-07-27-195509.json)

**Comment by chrisuthe** [comment]
Addressed in https://github.com/music-assistant/server/pull/5088 Thanks for the report @TheZoker

**Comment by tbgoose** [comment]
I am experiencing the same thing, any idea how long until the fix for this moves from dev to beta?

**Comment by OzGav** [comment]
Less than a week!

**Comment by mallorybowes** [comment]
I was getting the error and used Claude to debug.  Here's what I got...

Hitting this exact same error on 2.10.0b9 — confirmed it's a regression, and tracked down the root cause. Requesting this gets reopened, since there's now enough here to actually fix it.

**Confirmed regression:** works correctly on 2.10.0b3, breaks starting 2.10.0b9.

**Root cause:** `self.libraries` is only assigned inside `handle_async_init()`. But the `supported_features` property (audiobookshelf provider, line 376) reads `self.libraries` — and that property gets accessed by `rehydrate_provider_config()` *before* `handle_async_init()` has run:

```
mass.py:1208 _load_provider()
  → self.config.rehydrate_provider_config(provider)
    → controllers/config/providers.py:268 rehydrate_provider_config()
      → controllers/config/providers.py:631 _resolve_provider_config_entries()
        → controllers/config/providers.py:638 _wrap_provider_config_entries()
          → reads provider.supported_features
            → providers/audiobookshelf/__init__.py:376:
                if len(self.libraries.audiobooks) > 1 or len(self.libraries.podcasts) > 1:
                       ^^^^^^^^^^^^^^
                AttributeError: 'Audiobookshelf' object has no attribute 'libraries'
```

This looks like it was introduced alongside the `RecommendationPayloadMixin` integration — the provider class changed from `class Audiobookshelf(MusicProvider):` (2.10.0b3) to `class Audiobookshelf(RecommendationPayloadMixin, MusicProvider):` (2.10.0b9), and `self.libraries` is populated deep inside `handle_async_init()` specifically to support the new recommendations feature. Nothing guards `supported_features` against being read before that point in the provider lifecycle.

**Ruled out the dependency:** compared `aioaudiobookshelf` between the two MA versions (0.1.22 on b3, 0.1.24 on b9) — diffed the actual package source, no changes to the library-access API at all in that range. This is entirely within the provider code, not a dependency compatibility issue.

**Full traceback** (from the diagnostics `exceptions` section):

```
Traceback (most recent call last):
  File "music_assistant/mass.py", line 860, in load_provider
    await self.load_provider_config(prov_conf)
  File "music_assistant/mass.py", line 817, in load_provider_config
    await self._load_provider(prov_conf)
  File "music_assistant/mass.py", line 1208, in _load_provider
    await self.config.rehydrate_provider_config(provider)
  File "music_assistant/controllers/config/providers.py", line 268, in rehydrate_provider_config
    entries = await self._resolve_provider_config_entries(provider)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "music_assistant/controllers/config/providers.py", line 631, in _resolve_provider_config_entries
    return self._wrap_provider_config_entries(provider, await provider.get_config_entries())
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "music_assistant/controllers/config/providers.py", line 638, in _wrap_provider_config_entries
    provider.manifest, provider.supported_features, provider
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "music_assistant/providers/audiobookshelf/__init__.py", line 376, in supported_features
    if len(self.libraries.audiobooks) > 1 or len(self.libraries.podcasts) > 1:
           ^^^^^^^^^^^^^^
AttributeError: 'Audiobookshelf' object has no attribute 'libraries'
```

**Suggested fix direction:** either reorder provider loading so `handle_async_init()` (or at minimum the `self.libraries` assignment) runs before `rehydrate_provider_config()` reads `supported_features`, or make `supported_features` defensive against `self.libraries` not existing yet (e.g. `getattr(self, "libraries", None)` with a safe empty-library fallback) so it doesn't hard-crash provider loading before init completes.

Happy to test a fix against my own instance if that'd help!

**Comment by TheZoker** [comment]
@mallorybowes But you are aware, that this has already been fixed, right? 
No need to involve Claude if the fix is already done 😅

**Comment by mallorybowes** [comment]
@TheZoker Haha, I guess I'll give it another shot.  It wasn't working this morning and saw the waiting-for-user tag so thought you might've been waiting for op to provide more detail.  I'll re-pull the latest and give it a test.  Thx!

**Comment by mallorybowes** [comment]
Pulled fresh just now and still resolves to the same 2.10.0b9 image from this morning that I tested earlier (confirmed via org.opencontainers.image.version label, same digest as before). Doesn't look like a new beta has been published to the beta tag yet, so I don't think I've actually had a chance to test whatever fix landed.  (the beta I'm pulling is 4 days old so would make sense if you sent the fix but the MA beta isn't reflecting that yet...)  Thx again!

**Comment by mallorybowes** [comment]
Just following up my comment yesterday for anyone else that comes across.  Confirmed b10 fixed the issue.  Thx @TheZoker!
